apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  ports:
    - port: 8000
  selector:
    app: fastapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: projetokafka-fastapi:latest # minikube para uso local
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONPATH
              value: "/app"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017"
            - name: KAFKA_BROKER
              value: "kafka:29092"
